blog/urls.py
from django.urls import path
from blog.views import (

    create_blog_view,
    detail_blog_view,
    edit_blog_view,
)

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>', detail_blog_view, name="detail"),
    path('<slug>/edit', edit_blog_view, name="edit"),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import handler404, handler500
from django.contrib.auth import views as auth_views
from django.views.static import serve
from personal.views import (
    home_screen_view,
)
from mysite.views import custom_404, custom_500
from account.views import(
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)

handler404 = custom_404
handler500 = custom_500
admin.site.site_title = 'djBlogge Mgr.'
admin.site.site_header = 'djBlogge (A) Console'
admin.site.index_title = 'Webcare administration'

urlpatterns = [
    path('', home_screen_view, name="home"),
    path('admin/', admin.site.urls),
    path('account/', account_view, name="account"),
    path('blog/', include('blog.urls', 'blog')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.htm'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.htm'), 
        name='password_change'),

    path('password_reset/', 
        auth_views.PasswordResetView.as_view(
            template_name='registration/password_reset_form.htm',
            email_template_name='registration/password_reset_email.htm',
            subject_template_name='registration/password_reset_subject.htm'
            ), 
            name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.htm'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.htm'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.htm'), name='password_reset_complete'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),    
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

blog/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver


def upload_location(instance, filename, **kwargs):
    file_path = 'blog/{author_id}/{title}-{filename}'.format(
        author_id=str(instance.author.id), title=str(instance.title), filename=filename
        )
    return file_path

class BlogPost(models.Model):
    title                 = models.CharField(max_length=50, null=False, blank=False)
    body                  = models.TextField(max_length=10000, null=False, blank=False)
    image                 = models.ImageField(upload_to=upload_location, null=False, blank=False)
    date_published        = models.DateTimeField(auto_now_add=True, verbose_name="Date Published")
    date_updated          = models.DateTimeField(auto_now=True, verbose_name="Date Updated")
    author                = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug                  = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.title
    
@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)

def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)
    

blog/forms.py
from django import forms
from blog.models import BlogPost

class CreateBlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image']


class UpdateBlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ['title','body', 'image']

    def save(self, commit=True):
        blog_post = self.instance
        blog_post.title = self.cleaned_data['title']
        blog_post.body = self.cleaned_data['body']

        if self.cleaned_data['image']:
            blog_post.image = self.cleaned_data['image']

        if commit:
            blog_post.save()
        return blog_post

blog/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.db.models import Q
from django.http import HttpResponse
from blog.models import BlogPost
from blog.forms import CreateBlogPostForm, UpdateBlogPostForm
from account.models import Account

def create_blog_view(request):

    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')
    
    form =  CreateBlogPostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        obj.author = author
        obj.save()
        form = CreateBlogPostForm()
        context['success_message'] = 'Congrats! Your post has been published.'
    
    else:
        form = CreateBlogPostForm()

    context['form'] = form

    return render(request, "blog/create_blog.htm", context)


def detail_blog_view(request, slug):

    context = {}

    blog_post = get_object_or_404(BlogPost, slug=slug)
    context['blog_post'] = blog_post

    return render(request, 'blog/detail_blog.htm', context)


def edit_blog_view(request, slug):

    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect("must_authenticate")
    
    blog_post = get_object_or_404(BlogPost, slug=slug)

    if blog_post.author != user:
        return HttpResponse("🥲 Oops! Sorry, you are not authorized to perform this action. This action is restricted to the post’s author.")

    if request.POST:
        form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance=blog_post)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = "Post was updated"
            blog_post = obj
            return redirect('blog:detail', slug=blog_post.slug)


    form = UpdateBlogPostForm (
        initial = {
            "title": blog_post.title,
            "body": blog_post.body,
            "image": blog_post.image,
        } 
    )

    context['form'] = form
    return render(request, 'blog/edit_blog.htm', context)


def get_blog_queryset(query=None):
    queryset = []
    queries = query.split(" ")
    for search_query in queries:
        posts = BlogPost.objects.filter (
            Q(title__icontains=search_query) |
            Q(body__icontains=search_query)
        ).distinct()

        for post in posts:
            queryset.append(post)

    return list (set(queryset)) 

blog/templates/blog/create_blog.htm
<!DOCTYPE html>
<title>New post | djBlogge</title>

{% extends 'base.htm' %}

{% block content %}

<style>
.create-form {
background-color: transparent;
padding: 40px;
margin: 30px auto;
border-radius: 10px;
border: 1px solid #fff;
box-shadow: rgba(149, 157, 165, 0.2) 0px 8px 24px;
}

.form-group {
margin-bottom: 20px;
font-family: 'Jost', sans-serif;
}

.form-group label {
font-size: 18px;
font-weight: 600;
color: inherit;
margin-bottom: 10px;
display: block;
}

.form-control {
background-color: transparent;
color: inherit;
width: 100%;
padding: 10px;
font-size: 16px;
font-family: 'Jost', sans-serif;
border: none;
border-radius: 5px;
box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
}

.form-control:focus {
outline: none;
box-shadow: 0 0 0 2px rgba(0, 123, 255, 0.5);
}

.file-input {
display: inline-block;
position: relative;
cursor: pointer;
}

.file-input input[type="file"] {
position: absolute;
left: 0;
top: 0;
opacity: 0;
width: 100%;
height: 100%;
cursor: pointer;
}

.file-input .button {
background-color: transparent;
font-family: 'Jost', sans-serif;
color: #228bfb;
padding: 8px 16px;
border-radius: 5px;
border: 1px solid #ccc;
cursor: pointer;
}

.file-input .preview-image {
display: none;
max-width: 100%;
max-height: 200px;
margin-top: 10px;
}

.file-input .preview-image.show {
display: block;
}

.submit-button {
display: inline-block;
padding: 10px 20px;
background-color: #2e3339;
color: #fff;
border: 1px solid rgba(0, 123, 255, 0.5);
border-radius: 50px;
cursor: pointer;
transition: background-color 0.3s ease;
transform: scale(1.1);
font-family: 'Jost', sans-serif;
letter-spacing: 2px;
}

.submit-button:hover {
background-color: #1a1d20;
text-decoration: none;
color: #fff;
} 

.success-message {
margin-top: 10px;
padding: 10px;
font-family: 'Jost', sans-serif;
background-color: #d4edda;
border: 1px solid #c3e6cb;
color: #155724;
border-radius: 5px;
display: flex;
justify-content: space-between;
align-items: center;
letter-spacing: 0.5px;
}

.success-message .close-icon {
background-color: transparent;
cursor: pointer;
font-size: 20px;
transition: font-size 0.3s ease;
}

.close-icon {
border: 1px solid #155724;
color: #155724;
font-size: 20PX;
margin-left: 10px;
}

.success-message .close-icon:hover {
border: 1px solid #155724;
font-size: 24px;
}

.view-post-link {
text-decoration: none;
margin-left: 10px;
color: #155724;
transition: background-color 0.3s ease, border-radius 0.3s ease;
background-color: transparent;
border-radius: 5px;
}

.view-post-link:hover {
text-decoration: underline;
color: #155724;
}
</style>

{% if success_message %}
    <div class="success-message">
        <i class="fas fa-check-circle"></i>
        {{ success_message }}
        <a href="{% url 'home' %}" class="view-post-link">View Post</a>
        <button class="close-icon" type="button"><i class="fas fa-close"></i></button>
    </div>
{% endif %}

<div class="container">
    <div class="row">
        <div class="col-lg-7 offset-lg-1">
            <form class="create-form" method="post" enctype="multipart/form-data" onsubmit="submitButton.disabled = true; submitButton.innerHTML = '<i class=\'spinner-border spinner-border-sm\'></i> Posting...';">
                {% csrf_token %}
                <h2 style="text-align: center; margin-bottom: 30px; font-family: 'Jost',sans-serif; color: inherit;">
                    Create a New Post
                </h2>

                <div class="form-group">
                    <label for="id_title">Title</label>
                    <input class="form-control" type="text" name="title" id="id_title" placeholder="E.g. “Past for Future Generations”" required autofocus>
                </div>

                <div class="form-group">
                    <label for="id_body">Content</label>
                    <textarea class="form-control" rows="10" name="body" id="id_body" placeholder="What is happening?!" required></textarea>
                </div>

                <div class="form-group">
                    <label for="id_image">Image</label>
                    <div class="file-input">
                      <input type="file" name="image" id="id_image" accept="image/*" required>
                      <label class="button" for="id_image"><i class="fas fa-upload"></i> Upload</label>
                      <img class="preview-image" src="#" alt="Preview Image">
                    </div>
                </div>

                <button class="submit-button" type="submit" name="submitButton">
                    <i class="fas fa-paper-plane"></i> POST
                </button>
            </form>
        </div>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        var closeIcons = document.querySelectorAll(".close-icon");
        
        closeIcons.forEach(function(icon) {
        icon.addEventListener("click", function() {
            var successMessage = icon.parentNode;
            successMessage.parentNode.removeChild(successMessage);
        });
        
        icon.addEventListener("mouseover", function() {
        });
        
        icon.addEventListener("mouseout", function() {
            icon.style.color = "";
        });
        });
    });
    
    document.addEventListener("DOMContentLoaded", function() {
        var fileInput = document.getElementById("id_image");
        var previewImage = document.querySelector(".preview-image");

        fileInput.addEventListener("change", function() {
            var file = fileInput.files[0];
            if (file) {
            var reader = new FileReader();

            reader.onload = function(e) {
                previewImage.src = e.target.result;
                previewImage.classList.add("show");
            };

            reader.readAsDataURL(file);
            } else {
            previewImage.src = "#";
            previewImage.classList.remove("show");
            }
        });
    });
</script>
    

{% endblock content %}

blog/templates/blog/detail_blog.htm
<!DOCTYPE html>
<title>Post | djBlogge</title>

{% extends 'base.htm' %}

{% block content %}
<style type="text/css">
    .card {
    max-width: 700px;
    overflow: hidden;
    border: 1px solid #fff;
    border-radius: 10px;
    margin: auto;
    background-color: transparent;
    transition: box-shadow 0.3s;
    }

    .container {
    padding: 20px;
    }

    .card-img-top {
    width: calc(100% + 40px);
    margin-left: -20px;
    margin-right: -20px;
    height: auto;
    object-fit: cover;
    transition: box-shadow 0.2s;
    }

    .card-body {
    padding: 20px;
    }

    .card-title {
    font-size: 28px;
    font-weight: 600;
    margin-bottom: 10px;
    color: inherit;
    }

    .card-text {
    font-size: 18px;
    line-height: 1.6;
    color: inherit;
    }

    .card-footer {
    background-color: transparent;
    border-top: 1px solid #eaeaea;
    padding: 15px 20px;
    font-size: 14px;
    font-family: 'Jost', sans-serif;
    color: inherit;
    text-align: right;
    border-bottom-left-radius: 10px;
    border-bottom-right-radius: 10px;
    }

    .card-footer span {
    font-weight: bold;
    color: inherit;
    }

    .update-blog {
    display: inline-block;
    padding: 10px 20px;
    background-color: transparent;
    color: inherit;
    font-family: 'Jost', sans-serif;
    text-decoration: none;
    border: 1px solid;
    border-color: inherit;
    border-radius: 50px;
    transition: all 0.3s ease, color 0.3s;
    transform: scale(1.1);
    font-size: 16px;
    margin: 5px;
    }

    .update-blog:hover {
    background-color: #2e3339;
    color: #fff;
    border: 1px solid transparent;
    }
</style>

<div class="container">
    <div class="row">
        <div class="card">
            <img class="card-img-top" src="{{blog_post.image.url}}">
            <div class="card-body">
                <h2 class="card-title">{{blog_post.title}}</h2>
                <p class="card-text">{{blog_post.body|safe}}</p>
                {% if blog_post.author == request.user %}
                    <a href="{% url 'blog:edit' blog_post.slug %}" class="update-blog">
                        <i class="far fa-edit"></i> Edit post
                    </a>
                {% endif %}
            </div>
            <div class="card-footer">
                <span>Last updated:</span> {{blog_post.date_updated}} <span>by</span> {{blog_post.author}}
            </div>
        </div>
    </div>
</div>


{% endblock content %}

blog/templates/blog/edit_blog.htm
<!DOCTYPE html>
<title>Editing post | djBlogge</title>

{% extends 'base.htm' %}

{% block content %}

<style type="text/css">
    .create-form {
    font-family: 'Jost', sans-serif;
    max-width: 500px;
    margin: 50px auto;
    margin-top: 20px;
    padding: 20px;
    background-color: transparent;
    border: 1px solid #fff;
    border-radius: 8px;
    }

    .form-group {
    margin-bottom: 20px;
    }

    .form-group label {
    display: block;
    font-size: 18px;
    font-weight: bold;
    margin-bottom: 10px;
    }

    .form-group input,
    .form-group textarea {
    width: 100%;
    padding: 10px;
    font-size: 16px;
    font-family: 'Jost', sans-serif;
    border: none;
    color: inherit;
    border-radius: 5px;
    box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
    background-color: transparent;
    margin-bottom: 10px;
    }

    .form-group textarea {
    resize: vertical;
    }

    .form-group input:focus {
    box-shadow: 0 0 0 2px rgba(0, 123, 255, 0.5);
    }

    .form-group textarea:focus {
    box-shadow: 0 0 0 2px rgba(0, 123, 255, 0.5);
    }

    .image-group {
    position: relative;
    text-align: center;
    cursor: pointer;
    margin-bottom: 20px;
    font-family: 'Jost', sans-serif;
    }

    .image-group:hover .image {
    opacity: 0.3;
    }

    .image-group:hover .middle {
    opacity: 1;
    }

    .image {
    opacity: 1;
    transition: .5s ease;
    backface-visibility: hidden;
    margin-bottom: 10px;
    }

    .middle {
    transition: .5s ease;
    opacity: 0;
    position: absolute;
    text-align: center;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    }

    .text {
    margin: auto;
    background-color: #4CAF50;
    color: white;
    font-size: 15px;
    padding: 15px;
    }

    .update-edit {
    display: inline-block;
    padding: 10px 20px;
    background-color: #2e3339;
    color: #ffffff;
    font-family: 'Jost', sans-serif;
    text-decoration: none;
    border: none;
    border-radius: 50px;
    transition: background-color 0.2s ease;
    transform: scale(1.1);
    font-size: 16px;
    margin-top: 10px;
    cursor: pointer;
    }

    .update-edit:hover {
    background-color: #1a1d20;
    }

    .success-message {
    color: green;
    text-align: center;
    margin-bottom: 20px;
    }

    .error-message {
    color: red;
    margin-bottom: 10px;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-lg-7 offset-lg-2">
            {% if success_message %}
                <p class="success-message">{{ success_message }}</p>
            {% endif %}

            <form class="create-form" method="post" enctype="multipart/form-data" onsubmit="submitButton.disabled = true; submitButton.innerHTML = '<i class=\'spinner-border spinner-border-sm\'></i> Updating...';">
                {% csrf_token %}
                <h2 style="text-align: center; margin-bottom: 20px; font-family: 'Jost',sans-serif; color: inherit;">
                    Editing {{ form.initial.title }}
                </h2>

                <div class="form-group">
                    <label for="id_title">Title</label>
                    <input class="form-control" type="text" name="title" id="id_title" placeholder="E.g. “Past for Future Generations”" value="{{ form.initial.title }}" required autofocus>
                </div>

                <div class="form-group">
                    <label for="id_body">Content</label>
                    <textarea class="form-control" rows="10" name="body" id="id_body" placeholder="What is happening?!" required>{{ form.initial.body }}</textarea>
                </div>

                {% for field in form %}
                    {% if field.name != 'title' and field.name != 'body' %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {% for error in field.errors %}
                                <p class="error-message">{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                {% endfor %}

                <div class="form-group image-group" id="id_image_group" style="cursor: pointer;">
                    <img class="img-fluid image" src="{{ form.initial.image.url }}" id="id_image_display">
                    <div class="middle">
                        <div class="text">Change image</div>
                    </div>
                    <input type="file" name="image" id="id_image_file" accept="image/*" style="display: none;">
                </div>
                
                <div id="image-change-message" style="display: none;">Image has been changed</div>

                {% if form.non_field_errors %}
                    <div class="error-message">
                        {% for error in form.non_field_errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}

                <button class="update-edit" type="submit" name="submitButton">
                    <i class="fas fa-check"></i> Update
                </button>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    document.getElementById('id_image_group').onclick = function(event) {
        document.getElementById('id_image_file').click();
    };

    document.getElementById('id_image_file').onchange = function(event) {
        displaySelectedImage(this);
    };

    function displaySelectedImage(input) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $('#id_image_display').attr('src', e.target.result);
            document.getElementById('image-change-message').style.display = 'block';
        };
        reader.readAsDataURL(input.files[0]);
    }
</script>


{% endblock content %}