blog/urls.py
from django.urls import path
from blog.views import (

    create_blog_view,
    detail_blog_view,
    edit_blog_view,
)

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>', detail_blog_view, name="detail"),
    path('<slug>/edit', edit_blog_view, name="edit"),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import handler404, handler500
from django.contrib.auth import views as auth_views
from django.views.static import serve
from personal.views import (
    home_screen_view,
)
from mysite.views import custom_404, custom_500
from account.views import(
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)

handler404 = custom_404
handler500 = custom_500
admin.site.site_title = 'djBlogge Mgr.'
admin.site.site_header = 'djBlogge (A) Console'
admin.site.index_title = 'Webcare administration'

urlpatterns = [
    path('', home_screen_view, name="home"),
    path('admin/', admin.site.urls),
    path('account/', account_view, name="account"),
    path('blog/', include('blog.urls', 'blog')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.htm'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.htm'), 
        name='password_change'),

    path('password_reset/', 
        auth_views.PasswordResetView.as_view(
            template_name='registration/password_reset_form.htm',
            email_template_name='registration/password_reset_email.htm',
            subject_template_name='registration/password_reset_subject.htm'
            ), 
            name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.htm'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.htm'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.htm'), name='password_reset_complete'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),    
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

templates/snippets/footer.htm
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style type="text/css">
    .footer {
    background: #2e3339;
    color: #fff;
    padding: 20px;
    min-height: 100px;
    font-size: 14px;
    font-family: 'Jost', sans-serif;
    }

    .footer .footer-top {
    background: #2e3339 url("{% static 'footer-bg.png' %}") no-repeat right top;
    background-size: contain;
    border-bottom: 1px solid #555;
    padding: 60px 0 30px 0;
    }

    @media (max-width: 992px) {
        .footer .footer-top {
        background-position: center bottom;
        }
    }

    .footer .footer-top .footer-info {
    margin-bottom: 30px;
    }

    .footer .footer-top .footer-info .logo {
    line-height: 0;
    margin-bottom: 15px;
    cursor: pointer;
    }

    .footer .footer-top .footer-info .logo img {
    max-height: 40px;
    margin-right: 6px;
    }

    .footer .footer-top .footer-info .logo span {
    font-size: 30px;
    font-weight: 700;
    letter-spacing: 1px;
    color: #d0d4fc;
    font-family: 'Alike', serif;
    margin-top: 3px;
    }

    @media screen and (max-width: 767px) {
        .footer .footer-top .footer-info .logo span {
        font-size: 1.4rem;
        }
    }

    .footer .footer-top .footer-info p {
    font-size: 14px;
    line-height: 24px;
    margin-bottom: 0;
    font-family: 'Jost', sans-serif;
    }

    .footer .footer-top .social-links .x-twitter {
    font-size: 20px;
    fill: #f5f5f5;
    display: inline-block;
    line-height: 0;
    transform: translateY(-3px);
    transition: transform 0.3s, 0.3s;
    }

    .footer .footer-top .social-links .x-twitter:hover {
    fill: #d0d4fc;
    transform: translateY(-3px);
    }

    .footer .footer-top .social-links a {
    font-size: 20px;
    display: inline-block;
    color: #f5f5f5;
    line-height: 0;
    margin-right: 10px;
    transition: transform 0.3s, 0.3s;
    }

    .footer .footer-top .social-links a:hover {
    color: #d0d4fc;
    transform: translateY(-3px);
    }

    .footer .footer-top h4 {
    font-size: 16px;
    font-weight: bold;
    color: #d0d4fc;
    text-transform: uppercase;
    position: relative;
    padding-bottom: 12px;
    }

    .footer .footer-top .footer-links {
    margin-bottom: 30px;
    }

    .footer .footer-top .footer-links ul {
    list-style-type: none;
    list-style: none;
    padding: 0;
    margin: 0;
    }

    .footer .footer-top .footer-links ul i {
    padding-right: 2px;
    color: #d0d4fc;
    font-size: 12px;
    line-height: 0;
    }

    .footer .footer-top .footer-links ul li {
    padding: 10px 0;
    display: flex;
    align-items: center;
    }

    .footer .footer-top .footer-links ul li::before {
    content: "›";
    color: #d0d4fc;
    margin-right: 10px;
    }

    .footer .footer-top .footer-links ul li:first-child {
    padding-top: 0;
    }

    .footer .footer-top .footer-links ul a {
    color: #f5f5f5;
    transition: 0.3s;
    display: inline-block;
    line-height: 1;
    text-decoration: none;
    position: relative;
    font-size: 14px;
    }

    .footer .footer-top .footer-links ul a::before {
    content: '';
    position: absolute;
    left: 0;
    bottom: -4px;
    height: 4px;
    width: 100%;
    background-color: #d0d4fc;
    border-radius: 2px;
    transform: scaleX(0);
    transform-origin: left;
    transition: transform 0.3s ease-in-out;
    }

    .footer .footer-top .footer-links ul a:hover::before {
    transform: scaleX(1);
    }

    .footer .footer-top .footer-contact p {
    line-height: 26px;
    font-size: 14px;
    }

    .footer .footer-top .footer-contact p a {
    text-decoration: none;
    color: #f5f5f5;
    transition: 0.3s;
    position: relative;
    }

    .footer .footer-top .footer-contact p a::before {
    content: '';
    position: absolute;
    left: 0;
    bottom: -4px;
    height: 4px;
    width: 100%;
    background-color: #d0d4fc;
    border-radius: 2px;
    transform: scaleX(0);
    transform-origin: center;
    transition: transform 0.3s ease-in-out;
    }

    .footer .footer-top .footer-contact p a:hover::before {
    transform: scaleX(1);
    }

    .footer .copyright {
    text-align: center;
    padding-top: 30px;
    color: #fff;
    }

    .footer .credits {
    padding-top: 10px;
    text-align: center;
    font-size: 13px;
    color: #f5f5f5;
    }
    </style>
</head>


<!-- ======= Footer ======= -->
<footer id="footer" class="footer">
    <div class="footer-top">
        <div class="row gy-4">
            <div class="col-lg-5 col-md-12 footer-info">
            <div href="{% url 'home' %}" id="d-logo" title="djBlogge Hub" class="logo d-flex align-items-center">
                <img src="{% static 'djBlogge-icon.png' %}" alt="">
                <span>djBlogge</span>
            </div>
            <p>An exquisite, extraordinary all-round blogging and content hub! djBlogge is your go-to place for exciting content posts, gifted insights, and pure entertainment. 
                Plunge into a world of enthralling articles, cool ideas, and all-around good vibes. A content-packed, fun-filled scene like no other!
            </p>
            <div class="social-links mt-3">
                <a href="https://x.com/" title="X (Twitter)" class="twitter">
                    <svg xmlns="http://www.w3.org/2000/svg" height="1em" class="x-twitter" viewBox="0 0 512 512">
                        <path d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z"/>
                    </svg>
                </a>
                <a href="https://pinterest.com/" title="Pinterest" class="pinterest"><i class="fab fa-pinterest"></i></a>
                <a href="https://web.whatsapp.com/" title="WhatsApp" class="whatsapp"><i class="fab fa-whatsapp"></i></a>
                <a href="https://instagram.com/" title="Instagram" class="instagram"><i class="fab fa-instagram"></i></a>
                <a href="https://discord.com/" title="Discord" class="discord"><i class="fab fa-discord"></i></a>
            </div>
            </div>

            <div class="col-lg-2 col-6 footer-links">
            <h4>Navigation</h4>
            <ul>
                <li title="Home"> <a href="{% url 'home' %}">Home</a></li>
                <li title="Compose"> <a href="{% url 'blog:create' %}">Compose</a></li>
                <li title="About us"> <a href="#about">About us</a></li>
                <li title="Terms of service"> <a href="#tos">Terms of service</a></li>
                <li title="Privacy policy"> <a href="#privacy">Privacy policy</a></li>
            </ul>
            </div>

            <div class="col-lg-2 col-6 footer-links">
            <h4>More</h4>
            <ul>
                <li title="World"> <a href="#world">World</a></li>
                <li title="Today's opinion"> <a href="#opinion">Today's opinion</a></li>
                <li title="Today's arts"> <a href="#arts">Today's arts</a></li>
                <li title="djBlogge events"> <a href="#djb-events">Live events</a></li>
                <li title="Account"> <a href="{% url 'account' %}">Manage my account</a></li>
            </ul>
            </div>

            <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
            <h4>Get in Touch, Let's Talk..!</h4>
            <p>
                2033 Hercules Drive <br>
                Los Angeles, CA 90047<br>
                United States <br><br>
                <i class="fas fa-phone-volume" style="color: #d0d4fc;"></i> <a href="tel:+254107231945">+254 107 231 945</a><br>
                <i class="fas fa-envelope" style="color: #d0d4fc;"></i> <a href="mailto:devycotorg@gmail.com">hookon@djblogge.com</a><br>
            </p>

            </div>

        </div>
    </div>

    <div class="copyright">
        <span>&copy; <span id="current_year"></span> AY Corp. All rights reserved.</span>
    </div>

    <script>
        var currentYear = new Date().getFullYear();
        var currentYearElem = document.getElementById('current_year');
        if (currentYear && currentYear >= 2020) {
            currentYearElem.innerHTML = currentYear;
        } else {
            currentYearElem.innerHTML = 'Present';
        }

        document.getElementById("d-logo").addEventListener("click", function() {
            window.location.href = "{% url 'home' %}";
        });
    </script>
</footer><!-- End Footer -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>